BookJamm/BE

- config/database.js
> UPDATE: config 수정

- config/baseResponeStatus.js
- src/records/recordsController.js
- src/records/recordsDao.js
- src/records/recordsRouter.js
- src/records/recordsService.js
issue-18
issue-3
- friendId로 친구 기록 읽어오기
- friendId가 없으면 전체 친구 및 내 기록 읽어오기
- 기록 읽어올 때 가져올 값 수정
> Feat:18 GET friends records

- src/Activity/activityController.js
- src/Activity/activityDao.js
- src/Activity/activityProvider.js
- src/Activity/activityRoute.js
#3 
- 장소 아이디를 입력받았을 때 해당 장소에 대한 활동 다 보여 주는 기능 구현
- 기능 구현하고 없는 장소 검색했을 때 에러도 잘 뜹니다!!
일단 전체 칼럼 다 보이도록 했는데 나중에 가릴 정보 있으면 가리면 될 것 같아요!
> Feat: 장소 아이디를 입력받았을 때 해당 장소에 대한 활동 다 보여 주는 기능 구현

- config/baseResponeStatus.js
- config/express.js
- src/auth/authController.js
- src/auth/authDao.js
- src/auth/authProvider.js
- src/auth/authRouter.js
- email 형식 확인
- email 중복 확인
- email 형식 확인은 정규식을 이용해서 했습니다!
> POST /auth/email-check

- config/express.js
- src/records/recordsController.js
- src/records/recordsDao.js
- src/records/recordsRouter.js
- src/records/recordsService.js
- src/user/userController.js
- src/user/userDao.js
- src/user/userProvider.js
- src/user/userRouter.js
- src/user/userService.js
'/user', '/records' 나눔
issue 22
- GET /user/:userId/records -> 내 기록 보기
- POST /records -> 기록 쓰기
> Feat: 22 - user|records divide

- src/places/placesRouter.js
- 이전에 논의한 대로 장소 검색 API 엔드포인트 수정
> Update: search 라우터 주소 변경

- config/baseResponeStatus.js
- src/places/placesController.js
- src/places/placesDao.js
- src/places/placesRouter.js
- src/places/placesService.js
- 자주 사용되는 코드 및 변수는 추출해서 상단에 배치했습니다.
- 정렬 sql을 대대적으로 변경했습니다. (장소 검색 sql 포함)
> GET /places 카테고리 별 장소 API 구현

- .github/workflows/ci.yml
- package.json
> Revert "CI/CD update"

- .github/workflows/ci.yml
- package.json
> Revert "Revert "CI/CD update""

- .github/workflows/ci.yml
> Update: deploy.zip 디렉토리 수정

- config/baseResponeStatus.js
- src/places/placesController.js
- src/places/placesDao.js
- src/places/placesRouter.js
- src/places/placesService.js
#42 
- 소식이 없으면 소식 없다고, 장소가 없을 경우에는 장소가 없다고 에러 메시지 출력
> feat: 24 장소에 따른 소식 보여 주는 기능

- src/auth/authController.js
- src/auth/authDao.js
- src/auth/authProvider.js
- src/auth/authRouter.js
> feat: 32-auth/friends (친구 추천 세 명 보여 주는 api)

- src/user/userController.js
- src/user/userProvider.js
- src/user/userRouter.js
> Update: user put -> patch

- config/baseResponeStatus.js
- index.js
- src/records/recordsController.js
- src/records/recordsDao.js
- src/records/recordsProvider.js
- src/records/recordsRouter.js
- src/records/recordsService.js
- src/user/userController.js
- src/user/userRouter.js
/records/:recordId/images 추가, middleware 변경
issue-53
- middleware 변경
- /records/:recordId/images 추가
- /records 변경
> Update: /records, multer

- config/baseResponeStatus.js
- src/places/placesController.js
- src/places/placesDao.js
- src/places/placesRouter.js
- src/places/placesService.js
> feat: show books

- src/records/recordsController.js
- src/records/recordsDao.js
- src/records/recordsProvider.js
- src/records/recordsRouter.js
issue 60
- recordId에 대한 내용 수정
- recordId에 대한  images 삭제 (내용 수정할 때 다 지우고 다시 post 해야 될 것 같음)
> Feat: 60 - PUT /records/:recordId, DELETE /records/:recordId/images 

- src/auth/authProvider.js
- src/places/placesService.js
- src/records/recordsService.js
- src/reviews/reviewsService.js
release 하도록 수정
- service, provider에 `connection.release()`가 없는 함수들이 있어서 추가했습니다.
- connection을 끊지 않으면 DB에 connection이 쌓여서 리소스 고갈이 일어날 수 있다고 하네요!
- 다음부터는 service, provider 로직 구현 시 반.드.시. conneciton release 까먹지 않도록 주의 부탁드립니다!
> !HOTFIX: db connection release 해제

- config/express.js
- config/logger.js
- config/middlewares.js
- index.js
- package.json
- src/auth/authProvider.js
- src/places/placesService.js
- src/records/recordsService.js
- src/reviews/reviewsService.js
- winston: console.log를 대체하는 로그 기록 모듈
사용자가 찍은 로그를 자동으로 파일로 저장해주고 날짜별로 관리해줌
- morgan: 요청과 응답에 대한 로그를 자동으로 기록해주는 모듈
winston과 결합하여 morgan으로 생성된 로그들을 자동으로 winston이 받아서 파일로 저장, 관리해줌
- 배포했을 때 생길 수 있는 문제들을 쉽게 빠르게 추적하기 위해 추가하였습니다.
- 앞으로 서버에서 중요하게 찍힐 로그들이 있다면 winston 로그를 활용하면 좋을 것 같습니다!!
> winston, morgan 모듈을 이용한 log 기능 추가

- config/baseResponeStatus.js
- src/records/recordsController.js
- src/records/recordsDao.js
- src/records/recordsProvider.js
- src/records/recordsRouter.js
- src/records/recordsService.js
댓글 내용 수정
issue 69
- commentId에 해당하는 contents 수정
- userId를 받아서 댓글 작성자인지 확인 -> 댓글 작성자만 수정 가능
> Feat: 69 PATCH /records/comment/:commentId

- config/express.js
- package.json
- src/Activity/activityRouter.js
- src/activities/activitiesController.js
- src/activities/activitiesDao.js
- src/activities/activitiesProvider.js
- src/activities/activitiesRouter.js
- src/auth/authController.js
- src/auth/authDao.js
- src/auth/authProvider.js
- src/auth/authRouter.js
- src/auth/authService.js
> Feat/12 auth sign in 다시

- config/baseResponeStatus.js
- config/middlewares.js
- src/places/placesController.js
- src/places/placesRouter.js
- src/records/recordsController.js
- src/reviews/reviewsController.js
- src/reviews/reviewsDao.js
- src/reviews/reviewsProvider.js
- src/reviews/reviewsService.js
- src/users/usersController.js
- DELETE /reviews/:reviewId 수정
- 사용자 정보 받아와야 하는 API 헤더에서 받아오도록 수정
- JWT 만료 시 에러 응답 추가
- 리뷰 삭제 시 S3에서 이미지 삭제하는 로직은 없어서 추가 422e53fdbfefc2cedc1ef9927d95b44adcfacabb
- 사용자 정보가 필요한 API들 헤더에서 사용자 정보 추출할 수 있게 인증 추가 f6eab20ed0407853163463e67024e8e163ac9c17 f6eab20ed0407853163463e67024e8e163ac9c17
- JWT 만료 시 프런트에서 알 수 있는 방법이 없어서 에러 응답 추가함 35160cf7b7d35b20c46087d92b8326351ae19e7d
**❗️보노가 만든 것만 수정하였음!!! 다른 멤버들도 본인이 만든 API 수정해주기 바람❗️**
> 인증 미들웨어 추가 후 사용자 데이터 불러오기

- README.md
> Docs: build badge 추가

- config/baseResponeStatus.js
- config/logger.js
- src/users/usersController.js
- src/users/usersDao.js
- src/users/usersProvider.js
- src/users/usersRouter.js
- src/users/usersService.js
- 친구 삭제 기능 구현
- 개발 중일 때 로그 포맷 수정
- usersProvider, usersService에 잘 못 포함되어 있는 함수 이동
- 친구 삭제 기능 구현
- 개발 할 때 로그가 너무 난잡해보여서 프로덕션 환경일 때 로그랑 동일하게 찍히도록 수정함
- usersProvider와 usersService의 특성에 맞지 않는 함수들이 몇 개 있어서 수정 하였음
> Feature/84 delete following 친구 삭제 기능 추가

- config/baseResponeStatus.js
- config/s3.js
- src/auth/authController.js
- src/auth/authDao.js
- src/auth/authProvider.js
- src/auth/authService.js
- src/reviews/reviewsService.js
- src/users/usersController.js
- src/users/usersRouter.js
- 로그인 및 회원가입 controller try-catch로 묶어서 서버 터지지 않게 수정
- 회원가입, 로그인 로직 보안
- 그 외 사소한 부분 수정
fc6b7a582205e842064bbed09f53095ef77762d2
- try-catch문으로 묶어서 오류 발생 시 서버 터지지 않게 조치
- 요청 파라미터 validation (보안 및 에러 방지)
42cdbb52a7c3e67f552af9e5057ff5b32f491851
ae547107ebfa9bb186037cb9b5f0166bacb9d2be
- 중복되는 로직들이 많아 보여서 통합 및 삭제
f75cc3c1e7233f41004f52bffb52194edc97ed3a
- s3 이미지를 url로 삭제할 수 있게 로직 분리
53d455dfefcc41ca95e730f8ecf59970720698ce
- 프로필 이미지 변경 할 때 사진 여러개 올라갈 수 있도록 해놓아서 하나만 올라가도록 수정
> 회원가입, 로그인 로직 및 사소한 부분 보안

- config/s3.js
- src/records/recordsController.js
- src/records/recordsDao.js
- src/records/recordsService.js
- src/reviews/reviewsService.js
issue - 78
- deleteRecordImages 수정
- deleteS3Images 수정
- 이미지 id를 받아서 url 찾아오고 db와 s3 에 저장된 정보 모두 삭제
- deleteS3Images 코드 수정
> Feat/ 78 - DELETE /records/:recordId/images 수정

- src/records/recordsController.js
- src/records/recordsDao.js
- src/records/recordsProvider.js
- src/records/recordsRouter.js
- src/users/usersController.js
- src/users/usersDao.js
- src/users/usersProvider.js
- src/users/usersRouter.js
userId 받는 방법 변경, paging 추가,
/users/reviews, /users/activities 추가
issue 96
- users의 userId 받아오는 코드 수정(req.user.userId)
- /users/reviews, /users/activities 추가
- usersDao, recordsDao에 paging 추가
> Feat: 96 update users, records

- config/baseResponeStatus.js
- config/jwt.js
- config/middlewares.js
- src/auth/authController.js
- src/auth/authDao.js
- src/auth/authProvider.js
- src/auth/authRouter.js
- access token 만료시 refresh token으로 access token 재발급
- 한 번 사용한 refresh token은 폐기, 재발급
> GET /auth/refresh Access Token 재발급

- src/places/placesController.js
- src/places/placesDao.js
- src/places/placesService.js
- 장소 기본 정렬이 거리순으로 픽스됨에 따라 수정
- 이미지 아이디도 응답하도록 수정 
> GET /places 이미지 아이디도 함께 응답하도록 변경

- src/places/placesDao.js
- src/places/placesService.js
- [ x] 기능 추가
#102 
- 이미지 아이디도 반환하도록
> update: image 반환할 때 id도 같이 제출

- config/baseResponeStatus.js
- config/express.js
- package.json
- src/books/booksController.js
- src/books/booksProvider.js
- src/books/booksRouter.js
- src/records/recordsDao.js
#104 
- 제목으로 검색하기(5개)
- isbn으로 목록 데이터 불러오기
- 기록 저장하면 해당 장소에 책 추가하기
> Feat: 104 books apis

- src/auth/authDao.js
> !HOTFIX: authDao 중복 코드 삭제

- src/activities/activitiesController.js
- src/activities/activitiesDao.js
- src/activities/activitiesProvider.js
- 해당 jwt 토큰을 가진 사람이 좋아요를 누른 건지 boolean으로
> feat: 활동에 좋아요 있는지 표시

- src/auth/authController.js
- src/auth/authProvider.js
- 토큰 검증 로직 수정
- 객체를 잘 못 비교하였음...
> !HOTFIX!: 토큰 검증 로직 수정

- config/baseResponeStatus.js
- src/activities/activitiesController.js
- src/activities/activitiesDao.js
- src/activities/activitiesProvider.js
- src/activities/activitiesRouter.js
- src/activities/activitiesService.js
- 활동 좋아요 관련된 API 구현
- 좋아요 및 좋아요 취소 시 활동 존재 여부 및 좋아요 여부 검증
> 활동 좋아요 및 활동 좋아요 취소

- src/places/placesDao.js
- src/places/placesService.js
> 장소 검색 시 사진도 응답하도록 수정

- src/books/booksController.js
- src/books/booksProvider.js
- src/books/booksRouter.js
- src/places/placesDao.js
- src/places/placesService.js
Response books info
#128 
- 책 리스트 불러올 때, 책 정보 전달해주기
> feat: /places/:placeId/books response data update

- src/auth/authProvider.js
- src/auth/authService.js
- src/places/placesService.js
- src/users/usersProvider.js
- src/users/usersService.js
HOTFIX 입니다!
- connection release가 없어서 응답이 오지 않는 문제 해결
- connection release 하지 않는 service, provider 수정
> !HOTFIX!: GET /places/:placeId 터지는 현상 해결

- src/places/placesDao.js
> !HOTFIX!: image_url 응답 키 url로 수정

- src/places/placesDao.js
> update: place activities 보여 주는 api 카멜케이스 맞춤

- src/records/recordsController.js
- src/records/recordsDao.js
- src/records/recordsProvider.js
> fix: recordsDao fix

- src/records/recordsDao.js
- src/records/recordsProvider.js
- 피드에 작성자 닉네임, 프로필 이미지와 책 제목이 누락되어 수정
> HOTFIX: 피드에 작성자 닉네임, 프로필 이미지, 책 제목 추가

- config/baseResponeStatus.js
- src/places/placesController.js
- src/places/placesDao.js
- src/places/placesRouter.js
- src/places/placesService.js
Places bookmark update
#110 
- 장소 북마크 하기
> feat: POST /places/:placeId/bookmarks

- src/activities/activitiesDao.js
- src/places/placesDao.js
- src/users/usersDao.js
> HOTFIX: rating 소수점 둘 째자리까지 표시되게 변경

- src/users/usersDao.js
> HOTFIX: total_rating 변수명 추가

- src/activities/activitiesDao.js
- src/places/placesDao.js
- src/users/usersDao.js
> HOTFIX: rating float로 변경

- config/baseResponeStatus.js
- src/places/placesController.js
- src/places/placesDao.js
- src/places/placesRouter.js
- src/places/placesService.js
> feat: DELETE /places/:placeId/bookmarks
